language: php

php:
    - '5.6'    

before_script: 
    - git checkout develop
    - composer install

script: 
    - ./vendor/bin/phpunit tests

after_success:               
    - travis encrypt -r user/repo 'GITHUB_SECRET_TOKEN=0552a0e31ff68b8b0c64f6ce102eed1c76cd307d'  
    - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
    - "chmod a+x /tmp/travis-automerge"
    - "BRANCHES_TO_MERGE_REGEX='^f/' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=cdown/srt /tmp/travis-automerge"    