language: php

php:
    - '5.6'    

before_script: 
    - git checkout develop
    - composer install

script: 
    - ./vendor/bin/phpunit tests

after_success: 
    - git fetch master
    - git merge dev
    - git push origin master