language: php

php:
    - '5.6'    

before_script: 
    - git checkout develop
    - composer install

script: 
    - ./vendor/bin/phpunit tests
    - git checkout master
    - git merge develop
    - git push origin master

after_success: