branches:
  only:
    - master # Used for publishing releases automatically
    - develop
    
language: php

php:
    - '5.6'    
    
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG";
      cd "$TRAVIS_REPO_SLUG";
      git checkout -qf "$TRAVIS_COMMIT";
    fi
before_script: 
    - 'git checkout develop'
    - 'composer install'

script: 
    - './vendor/bin/phpunit tests'
before_deploy:
  - git config --global user.name arkadev # Replace!
  - git config --global user.email arkadevgroup@gmail.com # Replace!
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - git checkout master
  - npm run automatic-release # Here happens the magic
deploy:
  provider: npm
  email: arkadevgroup@gmail.com # Replace!
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    repo: arkadev/CIINTEGRATION # Replace!    
notifications:
  email:
    recipients:
    - jhonvegamas@hotmail.com    
    on_success: never # default: change
    on_failure: always # default: always