language: php

php:
    - '5.6'    

before_script: 
    - git checkout develop
    - composer install

script: 
    - phpunit --configuration tests/phpunit.xml

after_success: 
    - git checkout master
    - git merge dev
    - git push origin master